name: daikiri
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - _pytorch_select=0.2=gpu_0
  - absl-py=0.11.0=py37h89c1867_0
  - aiohttp=3.7.3=py37h5e8e339_1
  - argon2-cffi=20.1.0=py37h5e8e339_2
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyh44b312d_0
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py37h5e8e339_1001
  - c-ares=1.17.1=h36c2ea0_0
  - ca-certificates=2020.12.5=ha878542_0
  - cachetools=4.2.1=pyhd8ed1ab_0
  - certifi=2020.12.5=py37h89c1867_1
  - cffi=1.14.4=py37hc58025e_1
  - chardet=3.0.4=py37he5f6b98_1008
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=3.3.1=py37h7f0c10b_1
  - cudatoolkit=10.0.130=hf841e97_7
  - cudnn=7.6.5.32=ha8d7eb6_1
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - freetype=2.10.4=h5ab3b9f_0
  - fsspec=0.8.5=pyhd8ed1ab_0
  - future=0.18.2=py37h89c1867_3
  - google-auth=1.24.0=pyhd3deb0d_0
  - google-auth-oauthlib=0.4.1=py_2
  - grpcio=1.35.0=py37hb27c1af_0
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=3.4.0=py37h89c1867_0
  - importlib_metadata=1.5.0=py37_0
  - iniconfig=1.1.1=py_0
  - ipykernel=5.4.3=py37h888b3d9_0
  - ipython=7.20.0=py37h888b3d9_2
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.0=py37h89c1867_2
  - jinja2=2.11.3=pyh44b312d_0
  - joblib=1.0.0=pyhd8ed1ab_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.11=pyhd8ed1ab_1
  - jupyter_core=4.7.1=py37h89c1867_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_2
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - libffi=3.3=h58526e2_2
  - libgcc-ng=9.3.0=h2828fa1_18
  - libgfortran-ng=9.3.0=hff62375_18
  - libgfortran5=9.3.0=hff62375_18
  - liblapack=3.9.0=8_mkl
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.14.0=h780b84a_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=9.3.0=h6de172a_18
  - libtiff=4.1.0=h2733197_1
  - llvm-openmp=11.0.1=h4bd325d_0
  - lz4-c=1.9.3=h2531618_0
  - markdown=3.3.3=pyh9f0ad1d_0
  - markupsafe=1.1.1=py37h5e8e339_3
  - mistune=0.8.4=py37h5e8e339_1003
  - mkl=2020.4=h726a3e6_304
  - mkl-service=2.3.0=py37h8f50634_2
  - mkl_fft=1.2.0=py37h161383b_1
  - mkl_random=1.2.0=py37h9fdb41a_1
  - more-itertools=8.5.0=py_0
  - multidict=5.1.0=py37h5e8e339_1
  - nbclient=0.5.2=pyhd8ed1ab_0
  - nbconvert=6.0.7=py37h89c1867_3
  - nbformat=5.1.2=pyhd8ed1ab_1
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - ninja=1.10.2=h4bd325d_0
  - notebook=6.2.0=py37h89c1867_0
  - numpy=1.19.2=py37h54aff64_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - oauthlib=3.0.1=py_0
  - olefile=0.46=py37_0
  - openssl=1.1.1j=h7f98852_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.1=py37ha9443f7_0
  - pandoc=2.11.4=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.1=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.0=py37he98fc37_0
  - pip=21.0.1=pyhd8ed1ab_0
  - pluggy=0.13.1=py37_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.16=pyha770c72_0
  - protobuf=3.14.0=py37hcd2ae1e_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.8.0=pyhd8ed1ab_0
  - pyjwt=2.0.1=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py37h5e8e339_2
  - pysocks=1.7.1=py37h89c1867_3
  - pytest=6.1.1=py37_0
  - python=3.7.9=hffdb5ce_0_cpython
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.3.1=cuda100py37h53c1284_0
  - pytorch-lightning=1.1.8=pyhd8ed1ab_0
  - pytz=2021.1=pyhd3eb1b0_0
  - pyyaml=5.4.1=py37h5e8e339_0
  - pyzmq=20.0.0=py37h499b945_1
  - readline=8.0=he28a2e2_2
  - requests=2.25.1=pyhd3deb0d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.7=pyhd3deb0d_0
  - scikit-learn=0.24.1=py37h69acf81_0
  - scipy=1.6.0=py37h14a347d_0
  - send2trash=1.5.0=py_0
  - setuptools=49.6.0=py37h89c1867_3
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.34.0=h74cdb3f_0
  - tensorboard=2.4.1=pyhd8ed1ab_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - terminado=0.9.2=py37h89c1867_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=h21135ba_1
  - torchvision=0.4.2=cuda100py37hecfc37a_0
  - tornado=6.1=py37h5e8e339_1
  - tqdm=4.56.0=pyhd8ed1ab_0
  - traitlets=5.0.5=py_0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.26.3=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.6.3=py37h5e8e339_1
  - zeromq=4.3.4=h9c3ff4c_0
  - zipp=3.4.0=py_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - cloudpickle==2.0.0
    - cycler==0.10.0
    - dask==2021.10.0
    - isodate==0.6.0
    - kiwisolver==1.3.1
    - locket==0.2.1
    - matplotlib==3.3.4
    - partd==1.2.0
    - py==1.10.0
    - rdflib==6.0.2
    - toml==0.10.2
    - toolz==0.11.1
prefix: /home/demir/anaconda3/envs/daikiri
